# Supported funding platforms for node-red-contrib-onvif-ng

github: panthercomputers
liberapay: panthercomputers

# Optional direct links (kept minimal on purpose)
custom:
  - https://www.npmjs.com/package/node-red-contrib-onvif-ng
